AICP INTERNSHIP TASK-01



1. Write a Numpy program to create an array of all even integers from 30 to 70

In [2]:
import numpy as np

# Creating an array of all even integers from 30 to 70
even_integers = np.arange(30, 71, 2)

print("Array of even integers from 30 to 70:", even_integers)


Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


2. Write a numpy program to generate an array of 15 random numbers from a standard normal distribution

In [3]:
import numpy as np

# Generating an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.randn(15)

print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)


Array of 15 random numbers from a standard normal distribution:
[-0.6830748   2.08967924 -0.65293263 -1.36856841  0.47972693 -1.18235866
 -1.12774067 -1.24612618 -0.51478594 -0.68151079 -0.90766121 -1.23716519
  0.24861126  1.67402131  0.51227131]


3. How to compute the cross product of two matrices in Numpy?

In [4]:
import numpy as np

# Define two matrices (2-D arrays)
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

# Compute the cross product of the two matrices
cross_product = np.cross(matrix1, matrix2)

print("Cross product of the two matrices:")
print(cross_product)


Cross product of the two matrices:
[[-6 12 -6]
 [-6 12 -6]]


4. How to compute the determinant of an array using Numpy?

In [5]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2],
                   [3, 4]])

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print("Determinant of the matrix:", determinant)


Determinant of the matrix: -2.0000000000000004


5. How to create a 3x3x3 array with random values using Numpy?

In [6]:
import numpy as np

# Create a 3x3x3 array with random values
random_array = np.random.rand(3, 3, 3)

print("3x3x3 array with random values:")
print(random_array)


3x3x3 array with random values:
[[[0.09237486 0.14705131 0.45322515]
  [0.35936959 0.01718688 0.33734002]
  [0.72208664 0.14867946 0.73300834]]

 [[0.13758356 0.38980841 0.8415631 ]
  [0.34958795 0.14569743 0.64100694]
  [0.99082448 0.0075379  0.21302964]]

 [[0.49694502 0.54984057 0.48078242]
  [0.96439336 0.16288383 0.64647362]
  [0.28620404 0.11340431 0.54547065]]]


6. How to create a 5x5 array with random values and find the maximum and minimum values using Numpy?

In [7]:
import numpy as np

# Create a 5x5 array with random values
random_array = np.random.rand(5, 5)

print("5x5 array with random values:")
print(random_array)

# Find the maximum value in the array
max_value = np.max(random_array)

# Find the minimum value in the array
min_value = np.min(random_array)

print("Maximum value:", max_value)
print("Minimum value:", min_value)


5x5 array with random values:
[[0.98710623 0.06968273 0.15778943 0.46530506 0.11609365]
 [0.14945511 0.64143748 0.11843623 0.81607559 0.15299773]
 [0.00409632 0.64771173 0.1666681  0.76735521 0.07835327]
 [0.37331579 0.39967651 0.37949057 0.44044902 0.69657586]
 [0.87263167 0.70151214 0.43654928 0.27444472 0.16389036]]
Maximum value: 0.9871062259789865
Minimum value: 0.004096317530322358


7. How to compute the mean , standard deviation and variance of a given array along the second axis in Numpy?

In [8]:
import numpy as np

# Define the array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute the mean along the second axis (axis 1)
mean_values = np.mean(array, axis=1)

# Compute the standard deviation along the second axis (axis 1)
std_values = np.std(array, axis=1)

# Compute the variance along the second axis (axis 1)
variance_values = np.var(array, axis=1)

print("Mean along the second axis:", mean_values)
print("Standard deviation along the second axis:", std_values)
print("Variance along the second axis:", variance_values)


Mean along the second axis: [2. 5. 8.]
Standard deviation along the second axis: [0.81649658 0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667 0.66666667]
